### ISSUE TITLE
Delphi Win64 target

### ISSUE THREAD

**Issue by cairdac-rd** [BeRo1985/poca#2]
Hello,
Thank you for this great code.
Is the code supposed to compile with Delphi V10.3 (Rio) for Win64 platform ?

The function ``TPasMPInterlocked.ExchangeAdd`` is not defined.

```
procedure POCAMRSWLockReadUnlock(MRSWLock:PPOCAMRSWLock); {$ifdef cpu386}register;
asm
 lock dec dword ptr [eax+TPOCAMRSWLock.State]
end;
{$else}
begin
 TPasMPInterlocked.ExchangeAdd(MRSWLock^.State,-2);
end;
{$endif}
```
Regards,

**Comment by BeRo1985** [comment]
Should be fixed now, please test it.

**Comment by BeRo1985** [comment]
And you should use for Win64 better the FreePascal Compiler for POCA, because the Win64 FPC builds of POCA are often much faster than the Win64 Delphi Builds of POCA in my benchmark tests some time ago.

**Comment by cairdac-rd** [comment]
Hello,
Yes. it compiles now with Delphi for x64 platform. But it crashes at line 2686. the call stack is :
`` line 2686 if (Obj^.Header.GarbageCollector.State and pgcbNOWHITE)=0 then begin``
`` line 8429   if assigned(HashRec^.Events) then begin``
`` line 9344     POCAHashPut(HashInstance,HashRec,Key,Value);``
`` line 9490   POCAHashSet(Context,Hash,POCANewUniqueString(Context,Key),Value);``
``line 10419  POCAHashSetString(Context,result,'E',POCANumber(2.7182818284590452354));``
``line 12618  POCAHashSetString(Context,result,'Math',POCAInitMathNamespace(Context));``
``line 13832    result^.Globals.Namespace:=POCAInitGlobalNamespace(Context);``.

I tried also compiling it under linux x64 and got these errors.
```
fpc -B -O3 -g -gl pocarun.dpr
Free Pascal Compiler version 3.0.4+dfsg-18ubuntu2 [2018/08/29] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling pocarun.dpr
Compiling FLRE.pas
Compiling PUCU.pas
FLRE.pas(4845,5) Note: Local variable "Index" not used
FLRE.pas(4846,5) Note: Local variable "CurrentChar" not used
FLRE.pas(5013,5) Note: Local variable "Index" not used
FLRE.pas(5014,5) Note: Local variable "CurrentChar" not used
FLRE.pas(5174,5) Note: Local variable "Index" not used
FLRE.pas(5175,5) Note: Local variable "CurrentChar" not used
FLRE.pas(5357,5) Note: Local variable "Index" not used
FLRE.pas(5358,5) Note: Local variable "CurrentChar" not used
FLRE.pas(5474,5) Note: Local variable "Index" not used
FLRE.pas(5475,5) Note: Local variable "CurrentChar" not used
FLRE.pas(5642,5) Note: Local variable "Index" not used
FLRE.pas(5643,5) Note: Local variable "CurrentChar" not used
Compiling POCA.pas
Compiling PasDblStrUtils.pas
Compiling PasMP.pas
Compiling pthreads.pp
Compiling syncobjs.pp
Writing Resource String Table file: syncobjs.rsj
POCA.pas(8750,43) Error: Identifier not found "v"
POCA.pas(11293,77) Error: Identifier not found "CREATE_SUSPENDED"
POCA.pas(32658) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

**Comment by BeRo1985** [comment]
Okay, this should be fixed alsp now, please test it again. :-)

**Comment by cairdac-rd** [comment]
Yes :)
Great. It compile and run on both Win32 & Win64 with Delphi 10.3.2.

```
D:\Projects\Lang\poca\src>pocarun.exe fib.poca
fibR: 14930352
fibR time: 3875 milliseconds
D:\Projects\Lang\poca\src>pocarun_64.exe fib.poca
fibR: 14930352
fibR time: 4484 milliseconds
```

**Comment by BeRo1985** [comment]
Very good.
 
The define cpu64 was missing at the 64-bit x64 Delphi Build, which resulted in, among other things, that the NaN tagging stuff was still built as 32-bit variant and not as 64-bit variant. 

And for the case if you don't know, what NaN tagging is => https://nikic.github.io/2012/02/02/Pointer-magic-for-efficient-dynamic-value-representations.html and https://anniecherkaev.com/the-secret-life-of-nan and https://wingolog.org/archives/2011/05/18/value-representation-in-javascript-implementations and so on. 

And as a side note, most current 64-bit systems (all current x86-64 systems) have only a maximum memory address size of 48 bit, so the mantissa of 52 bit of a 64-bit double floating point value is sufficient here. And on newer 64-bit targets with larger than "possible" 48 bit virtual address size room, we do need to shift the actual pointer value by the alignment to fit it into 48 bits later then, which must be adjusted for each so such target, so that it fits after the bitshifting, what then has the disadvantage, that more memory is wasted then, due to the then higher allocation alignment per pooled object.
